### ISSUE TITLE
Add volume to state

### ISSUE THREAD

**Issue by RyuMaster** [xaya/taurion_gsp#73]
"inventory" : -{
"fungible" : -{
"silver prize" : 1
}
},

Need also to report total volume, as it might differ now for different item units

**Comment by domob1812** [comment]
We can add that, but not right now.  You can just use the same data list that I use from the roconfig protocol buffers.  Or just make it zero if there is a "prize" and one if there is none in the name for now.

**Comment by domob1812** [comment]
After #81, the general hardcoded data for the game (including the set of items and their volumes, but also other stuff that will be extended going forward) is saved as a binary protocol buffer in `proto/roconfig.pb` during build.

So the best solution here is to actually just load that file into the frontend as well.  In particular, the binary data corresponds to a [`ConfigData`](https://github.com/xaya/taurion_gsp/blob/master/proto/config.proto) proto message.  Item data can be found in the `fungible_items` [proto map](https://developers.google.com/protocol-buffers/docs/proto#maps).
