### ISSUE TITLE
missing 'prize'

### ISSUE THREAD

**Issue by RyuMaster** [xaya/taurion_gsp#74]
https://github.com/xaya/taurion_gsp/blob/546e45aa899e96ba22c6d66857999b1174993e9a/proto/roconfig/items.pb.text

"prize" missing for fungible prizes, hence it fails at:

> F1219 21:43:55.652307 18640 character.cpp:227] Check failed: mit != itemData.end () Unknown item in character inventory: Defender shotgun prize

adding ' prize' to the fungible item names at items.pb.text fixes it

**Comment by RyuMaster** [comment]
adding price is not a solution, as it will crash later inside moveprocessor when transferring items between inventories

**Comment by domob1812** [comment]
Thanks for the report, these were indeed two issues.  Fixed in 1a29c2127145d4e08b66844f473c1f7159bedd14 and 45061f50a748382a9c4fcfca0509d9656852c6fe.
