### ISSUE TITLE
Possible danger

### ISSUE THREAD

**Issue by RyuMaster** [xaya/taurion_gsp#75]
I thing, at move moveprocessor.cpp, here:

          const auto mit = itemData.find (entry.first);
          CHECK (mit != itemData.end ())
              << "Unknown item to be transferred: " << entry.first;

its possible to break GSP, if we push name update with drop/pu item with some random unsupported name. If will fail this check and broke GSP. Not 100% sure tho

**Comment by domob1812** [comment]
Fixed in 45061f50a748382a9c4fcfca0509d9656852c6fe, thanks for spotting this!
